name: CICD CineStream Frontend

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'web-film-frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

env:
  WORKING_DIR: web-film-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json

      - name: Build Frontend
        run: |
          cd ${{ env.WORKING_DIR }}
          npm install
          npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Prepare Frontend Directory on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/cinestream/frontend
            sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /var/www/cinestream/frontend

      - name: Push Dist to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "${{ env.WORKING_DIR }}/dist/*"
          target: "/var/www/cinestream/frontend"
          strip_components: 2
